const GITHUB_CLIENT_ID = process.env.GITHUB_CLIENT_ID;
const GITHUB_CLIENT_SECRET = process.env.GITHUB_CLIENT_SECRET;
const JWT_SECRET = process.env.JWT_SECRET;

export { GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, JWT_SECRET };
